"""Generated objective coverage for board-neutral GCSE Physics.

The catalogue follows the England GCSE single-science subject-content domains:
Energy, Electricity, Particle model of matter, Atomic structure, Forces,
Waves, Magnetism and electromagnetism, and Space physics.  Each objective has
a small generated question so it is immediately playable and can be checked by
the same content validator as the existing GCSE Maths catalogue.

The subject-content reference is the Department for Education's GCSE single
science publication: https://www.gov.uk/government/publications/gcse-single-science
"""

from __future__ import annotations

import random
import re

from .curriculum import Skill
from .generators import generator, mc

FOUNDATION_HIGHER = ("foundation", "higher")
HIGHER_ONLY = ("higher",)


def _generator_name(skill_id: str) -> str:
    return "coverage_" + re.sub(r"[^a-z0-9]+", "_", skill_id.lower()).strip("_")


def _physics_fact(
    sid: str,
    name: str,
    topic: str,
    tiers: tuple[str, ...],
    nc_ref: str,
    prompt: str,
    answer: str,
    distractors: tuple[str, str, str],
    hint: str = "",
) -> Skill:
    """Declare one generated, tier-aware Physics objective."""
    generator_name = _generator_name(sid)

    def question(rng: random.Random, level: int = 1) -> dict:
        return mc(
            prompt,
            answer,
            list(distractors),
            rng,
            hint=hint,
            explain=f"The correct answer is {answer}.",
        )

    question.__name__ = generator_name
    generator(generator_name)(question)
    return Skill(
        sid,
        name,
        "gcse_physics",
        topic,
        0,
        "generated",
        generator_name,
        nc_ref,
        (),
        "gcse_physics",
        tiers,
    )


# ---------------------------------------------------------------------------
# GCSE Physics — England single-science subject content
# ---------------------------------------------------------------------------

GCSE_PHYSICS_EXTRA: list[Skill] = [
    # Energy ----------------------------------------------------------------
    _physics_fact(
        "gcse.physics.energy.stores",
        "Energy stores",
        "Energy",
        FOUNDATION_HIGHER,
        "Describe energy stores, including kinetic, thermal, chemical, gravitational and elastic",
        "Which is an example of a chemical energy store?",
        "a battery",
        ("a moving car", "a stretched spring", "a hot radiator"),
    ),
    _physics_fact(
        "gcse.physics.energy.pathways",
        "Energy transfer pathways",
        "Energy",
        FOUNDATION_HIGHER,
        "Describe energy transfers by mechanical, electrical, heating and radiation pathways",
        "Which pathway transfers energy when a force moves an object?",
        "mechanically",
        ("electrically", "by sound only", "by mass"),
    ),
    _physics_fact(
        "gcse.physics.energy.conservation",
        "Conservation of energy",
        "Energy",
        FOUNDATION_HIGHER,
        "Apply the principle of conservation of energy",
        "In a closed system, energy is never what?",
        "created or destroyed",
        ("measured", "transferred", "stored"),
    ),
    _physics_fact(
        "gcse.physics.energy.work-done",
        "Work done",
        "Energy",
        FOUNDATION_HIGHER,
        "Calculate work done using force and distance moved in the direction of the force",
        "Work done equals force multiplied by what?",
        "distance moved in the direction of the force",
        ("mass", "time", "potential difference"),
    ),
    _physics_fact(
        "gcse.physics.energy.power",
        "Power",
        "Energy",
        FOUNDATION_HIGHER,
        "Calculate power as the rate of transfer of energy",
        "Power is the rate of transfer of what?",
        "energy",
        ("mass", "charge only", "momentum"),
    ),
    _physics_fact(
        "gcse.physics.energy.efficiency",
        "Efficiency",
        "Energy",
        FOUNDATION_HIGHER,
        "Calculate and compare efficiency using useful output and total input energy",
        "Efficiency is useful output energy divided by what?",
        "total input energy",
        ("time taken", "mass of the device", "input power only"),
    ),
    _physics_fact(
        "gcse.physics.energy.efficiency-calculation",
        "Efficiency calculations",
        "Energy",
        FOUNDATION_HIGHER,
        "Calculate efficiency as a percentage",
        "A machine gives 80 J of useful energy from 100 J input. What is its efficiency?",
        "80%",
        ("20%", "100%", "125%"),
    ),
    _physics_fact(
        "gcse.physics.energy.kinetic",
        "Kinetic energy",
        "Energy",
        FOUNDATION_HIGHER,
        "Use the kinetic energy equation",
        "Which expression gives the kinetic energy of an object?",
        "½mv²",
        ("mv", "mgh", "F ÷ d"),
    ),
    _physics_fact(
        "gcse.physics.energy.gravitational",
        "Gravitational potential energy",
        "Energy",
        FOUNDATION_HIGHER,
        "Use the gravitational potential energy equation",
        "Which expression gives gravitational potential energy near Earth?",
        "mgh",
        ("½mv²", "F ÷ A", "V ÷ I"),
    ),
    _physics_fact(
        "gcse.physics.energy.resources",
        "Energy resources",
        "Energy",
        FOUNDATION_HIGHER,
        "Compare renewable and non-renewable energy resources",
        "Which energy resource is renewable?",
        "wind",
        ("coal", "natural gas", "uranium fuel"),
    ),
    _physics_fact(
        "gcse.physics.energy.resource-evaluation",
        "Evaluating energy resources",
        "Energy",
        FOUNDATION_HIGHER,
        "Evaluate energy resources using reliability, environmental impact and power output",
        "Which factor describes whether a resource can provide energy when needed?",
        "reliability",
        ("its colour", "the mass of one electron", "the length of a wire"),
    ),
    _physics_fact(
        "gcse.physics.energy.high-voltage",
        "Energy losses in transmission",
        "Energy",
        FOUNDATION_HIGHER,
        "Explain why electricity is transmitted at high potential difference",
        "Why does a high transmission voltage reduce heating losses?",
        "It allows a smaller current for the same power.",
        ("It increases the resistance of every cable.", "It stops charge moving.", "It makes the cables colder directly."),
    ),

    # Electricity -----------------------------------------------------------
    _physics_fact(
        "gcse.physics.electricity.current",
        "Current and charge",
        "Electricity",
        FOUNDATION_HIGHER,
        "Use the relationship between charge, current and time",
        "Current is the rate of flow of what?",
        "charge",
        ("energy", "mass", "resistance"),
    ),
    _physics_fact(
        "gcse.physics.electricity.potential-difference",
        "Potential difference",
        "Electricity",
        FOUNDATION_HIGHER,
        "Explain potential difference as energy transferred per unit charge",
        "Potential difference is energy transferred per unit what?",
        "charge",
        ("time", "mass", "length"),
    ),
    _physics_fact(
        "gcse.physics.electricity.series-current",
        "Current in series circuits",
        "Electricity",
        FOUNDATION_HIGHER,
        "Explain that current is the same everywhere in a series circuit",
        "In a series circuit, the current is what at every point?",
        "the same",
        ("zero", "largest near the battery only", "different in every component"),
    ),
    _physics_fact(
        "gcse.physics.electricity.series-potential",
        "Potential difference in series circuits",
        "Electricity",
        FOUNDATION_HIGHER,
        "Explain how potential difference is shared between components in series",
        "In a series circuit, the supply potential difference equals what?",
        "the sum of the component potential differences",
        ("the largest resistance only", "zero", "the current multiplied by time"),
    ),
    _physics_fact(
        "gcse.physics.electricity.parallel-potential",
        "Potential difference in parallel circuits",
        "Electricity",
        FOUNDATION_HIGHER,
        "Explain that parallel branches have the same potential difference",
        "In parallel branches connected to one supply, the potential difference is what?",
        "the same across each branch",
        ("zero in every branch", "shared equally as current", "always greater in the longest branch"),
    ),
    _physics_fact(
        "gcse.physics.electricity.resistance",
        "Resistance",
        "Electricity",
        FOUNDATION_HIGHER,
        "Use the relationship between potential difference, current and resistance",
        "Resistance equals potential difference divided by what?",
        "current",
        ("charge", "power", "time"),
    ),
    _physics_fact(
        "gcse.physics.electricity.ohms-law",
        "Ohm's law",
        "Electricity",
        FOUNDATION_HIGHER,
        "Interpret current-potential difference graphs for ohmic conductors",
        "For a fixed-temperature ohmic conductor, current is directly proportional to what?",
        "potential difference",
        ("mass", "time only", "the colour of the wire"),
    ),
    _physics_fact(
        "gcse.physics.electricity.power",
        "Electrical power",
        "Electricity",
        FOUNDATION_HIGHER,
        "Use the relationship between power, current and potential difference",
        "Electrical power equals current multiplied by what?",
        "potential difference",
        ("resistance only", "charge squared", "mass"),
    ),
    _physics_fact(
        "gcse.physics.electricity.energy",
        "Electrical energy",
        "Electricity",
        FOUNDATION_HIGHER,
        "Calculate energy transferred using power and time",
        "Energy transferred by an appliance equals power multiplied by what?",
        "time",
        ("resistance", "charge density", "mass"),
    ),
    _physics_fact(
        "gcse.physics.electricity.domestic-safety",
        "Domestic electrical safety",
        "Electricity",
        FOUNDATION_HIGHER,
        "Explain the purpose of the live, neutral and earth wires and fuses",
        "What is the purpose of a fuse?",
        "It melts and breaks the circuit if the current is too large.",
        ("It stores charge for later.", "It increases the supply voltage.", "It makes current flow in reverse."),
    ),
    _physics_fact(
        "gcse.physics.electricity.earthing",
        "Earthing and insulation",
        "Electricity",
        FOUNDATION_HIGHER,
        "Explain how earthing and double insulation reduce electric shock risk",
        "The earth wire provides a low-resistance path if a metal case becomes what?",
        "live",
        ("transparent", "magnetic", "insulated by plastic"),
    ),
    _physics_fact(
        "gcse.physics.electricity.static",
        "Static electricity",
        "Electricity",
        FOUNDATION_HIGHER,
        "Explain static charge as an imbalance of electrons",
        "Static charge is usually caused by a transfer of which particles?",
        "electrons",
        ("protons between nuclei", "neutrons", "atoms of metal only"),
    ),
    _physics_fact(
        "gcse.physics.electricity.static-force",
        "Forces between charged objects",
        "Electricity",
        FOUNDATION_HIGHER,
        "Describe attraction and repulsion between charged objects",
        "Two objects with the same type of charge will what?",
        "repel",
        ("always attract", "lose all their mass", "become neutral immediately"),
    ),
    _physics_fact(
        "gcse.physics.electricity.resistance-factors",
        "Factors affecting resistance",
        "Electricity",
        FOUNDATION_HIGHER,
        "Describe how wire length, cross-sectional area and temperature affect resistance",
        "For the same material, a longer wire generally has what resistance?",
        "greater",
        ("smaller", "zero", "the same regardless of length"),
    ),

    # Particle model of matter --------------------------------------------
    _physics_fact(
        "gcse.physics.particles.density",
        "Density",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Use the relationship between mass, volume and density",
        "Density equals mass divided by what?",
        "volume",
        ("area", "time", "temperature"),
    ),
    _physics_fact(
        "gcse.physics.particles.solid",
        "Particle arrangement in solids",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Explain the arrangement and motion of particles in solids",
        "In a solid, particles vibrate around what?",
        "fixed positions",
        ("a vacuum only", "random new elements", "the outside surface"),
    ),
    _physics_fact(
        "gcse.physics.particles.states",
        "States of matter",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Use the particle model to explain differences between solids, liquids and gases",
        "Which state has particles that are far apart and move freely?",
        "gas",
        ("solid", "liquid only", "a crystal lattice"),
    ),
    _physics_fact(
        "gcse.physics.particles.changes-state",
        "Changes of state",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Explain changes of state in terms of energy and particle arrangement",
        "During melting, the substance gains energy but its temperature normally does what?",
        "stays constant",
        ("falls to absolute zero", "doubles every second", "becomes negative"),
    ),
    _physics_fact(
        "gcse.physics.particles.specific-heat",
        "Specific heat capacity",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Use the specific heat capacity equation",
        "Which equation relates energy change, mass, specific heat capacity and temperature change?",
        "ΔE = mcΔθ",
        ("E = m ÷ cΔθ", "p = F ÷ A", "V = IR"),
    ),
    _physics_fact(
        "gcse.physics.particles.latent-heat",
        "Specific latent heat",
        "Particle model of matter",
        HIGHER_ONLY,
        "Use the specific latent heat equation",
        "Which equation gives energy needed for a change of state?",
        "E = mL",
        ("E = mcΔθ", "E = Pt", "F = ma"),
    ),
    _physics_fact(
        "gcse.physics.particles.gas-pressure",
        "Gas pressure",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Explain gas pressure in terms of particle collisions",
        "Gas pressure is caused by particles colliding with what?",
        "the walls of the container",
        ("only the centre of Earth", "a magnetic pole", "light rays"),
    ),
    _physics_fact(
        "gcse.physics.particles.gas-volume",
        "Pressure and volume",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Describe the relationship between pressure and volume for a fixed mass of gas",
        "At constant temperature, decreasing a gas volume generally makes its pressure what?",
        "greater",
        ("zero", "unchanged in all cases", "negative"),
    ),
    _physics_fact(
        "gcse.physics.particles.absolute-zero",
        "Absolute zero",
        "Particle model of matter",
        FOUNDATION_HIGHER,
        "Use the Kelvin scale and understand absolute zero",
        "Absolute zero is approximately what temperature on the Celsius scale?",
        "−273°C",
        ("0°C", "273°C", "−100°C"),
    ),

    # Atomic structure ------------------------------------------------------
    _physics_fact(
        "gcse.physics.atomic.structure",
        "Structure of the atom",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Describe atoms as a nucleus of protons and neutrons surrounded by electrons",
        "Which particles are found in the nucleus?",
        "protons and neutrons",
        ("electrons only", "photons and electrons", "neutrons and shells only"),
    ),
    _physics_fact(
        "gcse.physics.atomic.neutral-atom",
        "Neutral atoms",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Relate atomic number, mass number and charge",
        "A neutral atom has equal numbers of protons and what?",
        "electrons",
        ("neutrons", "nuclei", "photons"),
    ),
    _physics_fact(
        "gcse.physics.atomic.isotopes",
        "Isotopes",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Explain isotopes as atoms with the same proton number but different neutron numbers",
        "Isotopes of an element have the same number of what?",
        "protons",
        ("neutrons", "electron shells", "nucleons in total"),
    ),
    _physics_fact(
        "gcse.physics.atomic.alpha",
        "Alpha radiation",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Describe alpha radiation as a helium nucleus",
        "An alpha particle contains how many protons and neutrons?",
        "two protons and two neutrons",
        ("one electron", "one proton and one neutron", "two electrons and two photons"),
    ),
    _physics_fact(
        "gcse.physics.atomic.beta",
        "Beta radiation",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Describe beta radiation as a fast electron emitted from the nucleus",
        "Beta-minus radiation is a fast-moving what?",
        "electron",
        ("helium nucleus", "neutron star", "gamma photon only"),
    ),
    _physics_fact(
        "gcse.physics.atomic.gamma",
        "Gamma radiation",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Describe gamma radiation as electromagnetic radiation",
        "Gamma radiation is a form of what?",
        "electromagnetic radiation",
        ("sound wave", "alpha particle", "slow neutron"),
    ),
    _physics_fact(
        "gcse.physics.atomic.penetration",
        "Penetration and ionisation",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Compare the ionising power and penetration of alpha, beta and gamma radiation",
        "Which common radiation type is the most penetrating?",
        "gamma",
        ("alpha", "beta", "visible light only"),
    ),
    _physics_fact(
        "gcse.physics.atomic.half-life",
        "Half-life",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Use half-life to describe radioactive decay",
        "The half-life is the time for the number of undecayed nuclei to fall to what fraction?",
        "one half",
        ("zero instantly", "one tenth", "double"),
    ),
    _physics_fact(
        "gcse.physics.atomic.activity",
        "Activity and becquerels",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Use the becquerel as a unit of radioactive activity",
        "One becquerel represents how many nuclear decays per second?",
        "one",
        ("one hundred", "one thousand", "zero"),
    ),
    _physics_fact(
        "gcse.physics.atomic.fission",
        "Nuclear fission",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Describe nuclear fission as the splitting of a large nucleus",
        "Nuclear fission is the splitting of what?",
        "a large atomic nucleus",
        ("a visible-light wave", "a small electron shell", "a chemical bond only"),
    ),
    _physics_fact(
        "gcse.physics.atomic.fusion",
        "Nuclear fusion",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Describe nuclear fusion as the joining of small nuclei",
        "Nuclear fusion joins what?",
        "small atomic nuclei",
        ("two electric circuits", "electron shells only", "two sound waves"),
    ),
    _physics_fact(
        "gcse.physics.atomic.safety",
        "Uses and risks of radiation",
        "Atomic structure",
        FOUNDATION_HIGHER,
        "Explain uses of radiation and precautions that reduce exposure",
        "Which measure reduces exposure to a radioactive source?",
        "increase distance from the source",
        ("hold it for longer", "remove all shielding", "reduce the distance"),
    ),

    # Forces ----------------------------------------------------------------
    _physics_fact(
        "gcse.physics.forces.scalars-vectors",
        "Scalars and vectors",
        "Forces",
        FOUNDATION_HIGHER,
        "Distinguish between scalar and vector quantities",
        "Which quantity is a vector?",
        "force",
        ("speed", "distance", "temperature"),
    ),
    _physics_fact(
        "gcse.physics.forces.contact",
        "Contact and non-contact forces",
        "Forces",
        FOUNDATION_HIGHER,
        "Identify contact and non-contact forces",
        "Which is a non-contact force?",
        "gravitational force",
        ("friction", "air resistance", "tension in a rope"),
    ),
    _physics_fact(
        "gcse.physics.forces.resultant",
        "Resultant force",
        "Forces",
        FOUNDATION_HIGHER,
        "Calculate and interpret resultant forces",
        "If the resultant force on an object is zero, its motion is what?",
        "constant, or the object is stationary",
        ("always accelerating", "always slowing", "impossible to predict"),
    ),
    _physics_fact(
        "gcse.physics.forces.speed",
        "Speed",
        "Forces",
        FOUNDATION_HIGHER,
        "Calculate speed from distance and time",
        "Speed equals distance divided by what?",
        "time",
        ("mass", "force", "area"),
    ),
    _physics_fact(
        "gcse.physics.forces.velocity",
        "Velocity",
        "Forces",
        FOUNDATION_HIGHER,
        "Distinguish velocity from speed",
        "Velocity is speed in a stated what?",
        "direction",
        ("mass", "temperature", "material"),
    ),
    _physics_fact(
        "gcse.physics.forces.acceleration",
        "Acceleration",
        "Forces",
        FOUNDATION_HIGHER,
        "Calculate acceleration from change in velocity and time",
        "Acceleration equals change in velocity divided by what?",
        "time",
        ("distance only", "mass", "potential difference"),
    ),
    _physics_fact(
        "gcse.physics.forces.velocity-time",
        "Velocity-time graphs",
        "Forces",
        FOUNDATION_HIGHER,
        "Interpret the gradient and area of velocity-time graphs",
        "The gradient of a velocity-time graph gives what?",
        "acceleration",
        ("mass", "density", "energy store"),
    ),
    _physics_fact(
        "gcse.physics.forces.newton-second",
        "Newton's second law",
        "Forces",
        FOUNDATION_HIGHER,
        "Use the relationship between force, mass and acceleration",
        "Which equation represents Newton's second law?",
        "F = ma",
        ("p = mv", "E = Pt", "V = IR"),
    ),
    _physics_fact(
        "gcse.physics.forces.weight",
        "Weight",
        "Forces",
        FOUNDATION_HIGHER,
        "Use the relationship between weight, mass and gravitational field strength",
        "Weight equals mass multiplied by what?",
        "gravitational field strength",
        ("velocity", "density", "specific heat capacity"),
    ),
    _physics_fact(
        "gcse.physics.forces.terminal-velocity",
        "Terminal velocity",
        "Forces",
        FOUNDATION_HIGHER,
        "Explain terminal velocity using weight, drag and resultant force",
        "At terminal velocity, the resultant force is what?",
        "zero",
        ("equal to the weight twice", "maximum", "always downward"),
    ),
    _physics_fact(
        "gcse.physics.forces.stopping-distance",
        "Stopping distance",
        "Forces",
        FOUNDATION_HIGHER,
        "Explain thinking distance and braking distance",
        "Stopping distance is the sum of thinking distance and what?",
        "braking distance",
        ("displacement only", "mass distance", "wave distance"),
    ),
    _physics_fact(
        "gcse.physics.forces.work",
        "Work done by a force",
        "Forces",
        FOUNDATION_HIGHER,
        "Calculate work done when a force moves an object",
        "When force and movement are in the same direction, work done is force multiplied by what?",
        "distance",
        ("current", "mass density", "time squared"),
    ),
    _physics_fact(
        "gcse.physics.forces.moments",
        "Moments",
        "Forces",
        FOUNDATION_HIGHER,
        "Calculate moments using force and perpendicular distance from a pivot",
        "A moment equals force multiplied by perpendicular distance from what?",
        "the pivot",
        ("the centre of mass only", "the battery", "the wave source"),
    ),
    _physics_fact(
        "gcse.physics.forces.pressure",
        "Pressure",
        "Forces",
        FOUNDATION_HIGHER,
        "Use the relationship between force, area and pressure",
        "Pressure equals force divided by what?",
        "area",
        ("volume", "time", "mass"),
    ),
    _physics_fact(
        "gcse.physics.forces.hooke-law",
        "Force and extension",
        "Forces",
        FOUNDATION_HIGHER,
        "Describe the relationship between force and extension for an elastic object",
        "For a spring obeying Hooke's law, extension is proportional to what?",
        "force",
        ("mass only", "temperature only", "volume"),
    ),
    _physics_fact(
        "gcse.physics.forces.elasticity",
        "Elastic and inelastic deformation",
        "Forces",
        FOUNDATION_HIGHER,
        "Distinguish elastic deformation from inelastic deformation",
        "An elastic deformation is one where the object returns to what?",
        "its original shape when the force is removed",
        ("absolute zero", "a larger mass", "a random shape only"),
    ),
    _physics_fact(
        "gcse.physics.forces.momentum",
        "Momentum",
        "Forces",
        HIGHER_ONLY,
        "Use the relationship between momentum, mass and velocity",
        "Momentum equals mass multiplied by what?",
        "velocity",
        ("acceleration squared", "density", "potential difference"),
    ),
    _physics_fact(
        "gcse.physics.forces.momentum-conservation",
        "Conservation of momentum",
        "Forces",
        HIGHER_ONLY,
        "Apply conservation of momentum to collisions and explosions",
        "In a closed system, total momentum before an interaction is what compared with total momentum after?",
        "the same",
        ("always zero", "always doubled", "smaller in every collision"),
    ),

    # Waves -----------------------------------------------------------------
    _physics_fact(
        "gcse.physics.waves.properties",
        "Wave properties",
        "Waves",
        FOUNDATION_HIGHER,
        "Describe amplitude, wavelength, frequency and period",
        "The distance from one crest to the next crest is the what?",
        "wavelength",
        ("amplitude", "period only", "wavefront speed"),
    ),
    _physics_fact(
        "gcse.physics.waves.transverse-longitudinal",
        "Transverse and longitudinal waves",
        "Waves",
        FOUNDATION_HIGHER,
        "Distinguish transverse and longitudinal waves",
        "In a transverse wave, oscillations are perpendicular to which direction?",
        "energy transfer",
        ("the colour of the source", "the mass of the medium", "the temperature scale"),
    ),
    _physics_fact(
        "gcse.physics.waves.wave-speed",
        "Wave speed",
        "Waves",
        FOUNDATION_HIGHER,
        "Use the wave speed equation",
        "Wave speed equals frequency multiplied by what?",
        "wavelength",
        ("amplitude", "mass", "resistance"),
    ),
    _physics_fact(
        "gcse.physics.waves.reflection",
        "Reflection",
        "Waves",
        FOUNDATION_HIGHER,
        "Explain reflection using the angle of incidence and angle of reflection",
        "For reflection from a plane surface, the angle of incidence equals the angle of what?",
        "reflection",
        ("refraction", "diffraction", "dispersion only"),
    ),
    _physics_fact(
        "gcse.physics.waves.refraction",
        "Refraction",
        "Waves",
        FOUNDATION_HIGHER,
        "Explain refraction as a change in wave speed and direction",
        "Refraction happens when a wave changes speed as it enters a different what?",
        "medium",
        ("mass number", "circuit branch", "nuclear half-life"),
    ),
    _physics_fact(
        "gcse.physics.waves.sound",
        "Sound waves",
        "Waves",
        FOUNDATION_HIGHER,
        "Describe sound as a longitudinal wave requiring a medium",
        "Sound cannot travel through what?",
        "a vacuum",
        ("water", "air", "steel"),
    ),
    _physics_fact(
        "gcse.physics.waves.em-spectrum",
        "Electromagnetic spectrum",
        "Waves",
        FOUNDATION_HIGHER,
        "Recall the order and properties of the electromagnetic spectrum",
        "Which electromagnetic wave has the highest frequency?",
        "gamma rays",
        ("radio waves", "infrared", "microwaves"),
    ),
    _physics_fact(
        "gcse.physics.waves.visible-spectrum",
        "Visible light",
        "Waves",
        FOUNDATION_HIGHER,
        "Use the order of colours in the visible spectrum",
        "Which visible colour has the shortest wavelength?",
        "violet",
        ("red", "yellow", "green"),
    ),
    _physics_fact(
        "gcse.physics.waves.em-uses",
        "Uses of electromagnetic waves",
        "Waves",
        FOUNDATION_HIGHER,
        "Describe uses of electromagnetic radiation",
        "Which electromagnetic wave is commonly used for thermal imaging?",
        "infrared",
        ("gamma rays", "ultraviolet only", "radio waves only"),
    ),
    _physics_fact(
        "gcse.physics.waves.em-hazards",
        "Electromagnetic hazards",
        "Waves",
        FOUNDATION_HIGHER,
        "Explain hazards of ultraviolet, X-rays and gamma rays",
        "Which type of electromagnetic radiation can ionise atoms and damage cells?",
        "ionising radiation",
        ("all sound", "visible light only", "long-wave radio only"),
    ),
    _physics_fact(
        "gcse.physics.waves.lenses",
        "Lenses",
        "Waves",
        HIGHER_ONLY,
        "Use ray diagrams to explain image formation by converging and diverging lenses",
        "A converging lens brings parallel rays to a what?",
        "focus",
        ("nucleus", "pivot", "terminal velocity"),
    ),
    _physics_fact(
        "gcse.physics.waves.total-internal-reflection",
        "Total internal reflection",
        "Waves",
        HIGHER_ONLY,
        "Explain total internal reflection and its use in optical fibres",
        "Total internal reflection requires the angle of incidence to be greater than the what?",
        "critical angle",
        ("right angle only", "wavelength of sound", "half-life"),
    ),

    # Magnetism and electromagnetism ---------------------------------------
    _physics_fact(
        "gcse.physics.magnetism.fields",
        "Magnetic fields",
        "Magnetism and electromagnetism",
        FOUNDATION_HIGHER,
        "Describe magnetic fields around permanent magnets and current-carrying wires",
        "A magnetic field is the region where a magnetic material experiences what?",
        "a force",
        ("a temperature change only", "a nuclear decay", "a change in mass"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.poles",
        "Magnetic poles",
        "Magnetism and electromagnetism",
        FOUNDATION_HIGHER,
        "Describe attraction and repulsion between magnetic poles",
        "Like magnetic poles do what?",
        "repel",
        ("always attract", "become electric", "have no field"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.induced",
        "Induced magnetism",
        "Magnetism and electromagnetism",
        FOUNDATION_HIGHER,
        "Explain induced magnetism in magnetic materials",
        "Induced magnetism is usually what when the inducing magnet is removed?",
        "temporary",
        ("permanent in every material", "radioactive", "a type of sound"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.electromagnets",
        "Electromagnets",
        "Magnetism and electromagnetism",
        FOUNDATION_HIGHER,
        "Explain how current, turns and an iron core affect an electromagnet",
        "Which change usually makes a solenoid electromagnet stronger?",
        "increase the current",
        ("remove all turns", "use a plastic core only", "open the circuit"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.motor-effect",
        "The motor effect",
        "Magnetism and electromagnetism",
        FOUNDATION_HIGHER,
        "Explain how a current-carrying conductor experiences a force in a magnetic field",
        "The force on a current-carrying wire in a magnetic field is called what effect?",
        "the motor effect",
        ("the photoelectric effect", "the greenhouse effect", "the half-life effect"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.motor-force",
        "Motor-effect force",
        "Magnetism and electromagnetism",
        HIGHER_ONLY,
        "Use the relationship between magnetic flux density, current, length and force",
        "Which equation gives the force on a wire at right angles to a magnetic field?",
        "F = BIl",
        ("F = ma", "E = mcΔθ", "p = mv"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.generator",
        "Generator effect",
        "Magnetism and electromagnetism",
        FOUNDATION_HIGHER,
        "Explain electromagnetic induction in a moving conductor",
        "A changing magnetic field can induce a what?",
        "potential difference",
        ("mass", "half-life", "density only"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.transformers",
        "Transformers",
        "Magnetism and electromagnetism",
        FOUNDATION_HIGHER,
        "Explain how transformers change alternating potential difference",
        "A transformer works with which type of current?",
        "alternating current",
        ("steady direct current only", "static charge only", "sound current"),
    ),
    _physics_fact(
        "gcse.physics.magnetism.transformer-ratio",
        "Transformer turns ratio",
        "Magnetism and electromagnetism",
        HIGHER_ONLY,
        "Use the transformer turns-ratio equation",
        "In an ideal transformer, the output potential difference depends on the ratio of what?",
        "secondary turns to primary turns",
        ("mass to volume", "current to charge", "force to area"),
    ),

    # Space physics ---------------------------------------------------------
    _physics_fact(
        "gcse.physics.space.solar-system",
        "The Solar System",
        "Space physics",
        FOUNDATION_HIGHER,
        "Describe the structure of the Solar System",
        "Which object is at the centre of our Solar System?",
        "the Sun",
        ("Earth's Moon", "Polaris", "the Milky Way's edge"),
    ),
    _physics_fact(
        "gcse.physics.space.orbits",
        "Orbital motion",
        "Space physics",
        FOUNDATION_HIGHER,
        "Explain circular orbital motion as a changing velocity caused by gravity",
        "An object in a circular orbit is accelerating because its what changes?",
        "direction of velocity",
        ("mass disappears", "temperature becomes zero", "charge stops existing"),
    ),
    _physics_fact(
        "gcse.physics.space.satellites",
        "Artificial satellites",
        "Space physics",
        FOUNDATION_HIGHER,
        "Compare geostationary and low-orbit satellites",
        "A geostationary satellite has an orbital period of approximately what?",
        "24 hours",
        ("one second", "one year exactly", "one minute"),
    ),
    _physics_fact(
        "gcse.physics.space.stars",
        "Formation of stars",
        "Space physics",
        FOUNDATION_HIGHER,
        "Describe how stars form from clouds of gas and dust",
        "Stars form when gravity causes a cloud of gas and dust to what?",
        "collapse",
        ("evaporate instantly", "become a circuit", "lose all particles"),
    ),
    _physics_fact(
        "gcse.physics.space.main-sequence",
        "Main-sequence stars",
        "Space physics",
        FOUNDATION_HIGHER,
        "Describe the stable main-sequence stage of a star",
        "During the main-sequence stage, stars release energy mainly by what process?",
        "nuclear fusion",
        ("chemical combustion only", "friction with space", "fission of iron only"),
    ),
    _physics_fact(
        "gcse.physics.space.star-death",
        "The life cycle of stars",
        "Space physics",
        FOUNDATION_HIGHER,
        "Describe the later stages of low- and high-mass stars",
        "A low-mass star can end as a red giant followed by a what?",
        "white dwarf",
        ("black hole every time", "neutron star every time", "main-sequence planet"),
    ),
    _physics_fact(
        "gcse.physics.space.supernova",
        "Supernovae and remnants",
        "Space physics",
        FOUNDATION_HIGHER,
        "Describe supernovae and the formation of neutron stars or black holes",
        "A very massive star may end in a what?",
        "supernova",
        ("chemical battery", "lunar eclipse only", "static discharge"),
    ),
    _physics_fact(
        "gcse.physics.space.stellar-fusion",
        "Fusion in stars",
        "Space physics",
        FOUNDATION_HIGHER,
        "Explain that stars produce energy by nuclear fusion",
        "The main fusion process in a Sun-like star changes hydrogen into what?",
        "helium",
        ("uranium", "silicon circuits", "oxygen gas only"),
    ),
    _physics_fact(
        "gcse.physics.space.red-shift",
        "Red-shift",
        "Space physics",
        HIGHER_ONLY,
        "Explain red-shift as evidence that distant galaxies are moving away",
        "Red-shift in light from distant galaxies suggests that the galaxies are moving how?",
        "away from us",
        ("towards us only", "not moving at all", "inside the Solar System"),
    ),
    _physics_fact(
        "gcse.physics.space-big-bang",
        "The Big Bang model",
        "Space physics",
        HIGHER_ONLY,
        "Use red-shift and cosmic microwave background radiation as evidence for the Big Bang",
        "Which observation is evidence supporting the Big Bang model?",
        "cosmic microwave background radiation",
        ("the phases of the Moon", "Earth's seasons only", "a barometer reading"),
    ),
    _physics_fact(
        "gcse.physics.space-light-year",
        "Astronomical distances",
        "Space physics",
        FOUNDATION_HIGHER,
        "Use the light-year as a unit of astronomical distance",
        "A light-year is a unit of what?",
        "distance",
        ("time only", "brightness", "mass"),
    ),
]
